// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
//  WARNING: DO NOT COMMIT THIS FILE TO VERSION CONTROL WITH REAL API KEYS!
//
//  This file is generated by the FlutterFire CLI and contains your Firebase
//  project configuration. It's crucial to keep your API keys and other
//  sensitive information secure.
//
//  Replace the placeholder values below with your actual Firebase project
//  credentials BEFORE building your app for production.
//
//  For more information, see:
//  https://firebase.google.com/docs/flutter/setup#configure-your-app
//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: '1056652851968',
    projectId: 'rewardly-mini',
    authDomain: 'rewardly-mini.firebaseapp.com',
    databaseURL: 'https://rewardly-mini-default-rtdb.firebaseio.com',
    storageBucket: 'rewardly-mini.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: '1:1056652851968:android:349e8a91bf2d45c7a8d1e5',
    messagingSenderId: '1056652851968',
    projectId: 'rewardly-mini',
    databaseURL: 'https://rewardly-mini-default-rtdb.firebaseio.com',
    storageBucket: 'rewardly-mini.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:1056652851968:ios:a22ac4e13f19ab69a8d1e5',
    messagingSenderId: '1056652851968',
    projectId: 'rewardly-mini',
    databaseURL: 'https://rewardly-mini-default-rtdb.firebaseio.com',
    storageBucket: 'rewardly-mini.firebasestorage.app',
    iosBundleId: 'com.supreet.rewardly',
  );
}
