import 'package:flutter/material.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Privacy Policy'),
      ),
      body: const SingleChildScrollView(
        padding: EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Privacy Policy',
              style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 16),
            Text(
              'This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.',
            ),
            SizedBox(height: 16),
            Text(
              'Interpretation and Definitions',
              style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 8),
            Text(
              'The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.',
            ),
            SizedBox(height: 16),
            Text(
              'Definitions',
              style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 8),
            Text(
              'For the purposes of this Privacy Policy:',
            ),
            SizedBox(height: 8),
            Text(
              '  • Account means a unique account created for You to access our Service or parts of our Service.',
            ),
            Text(
              '  • Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Rewardly.',
            ),
            Text(
              '  • Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.',
            ),
            Text(
              '  • Country refers to: United States',
            ),
            Text(
              '  • Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.',
            ),
            Text(
              '  • Personal Data is any information that relates to an identified or identifiable individual.',
            ),
            Text(
              '  • Service refers to the Website.',
            ),
            Text(
              '  • Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.',
            ),
            Text(
              '  • Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).',
            ),
            Text(
              '  • Website refers to Rewardly, accessible from https://rewardly.com',
            ),
            Text(
              '  • You means the individual access or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.',
            ),
          ],
        ),
      ),
    );
  }
}
